import { PDFDocument, rgb, StandardFonts } from "pdf-lib"

export interface LegalPacketData {
  tenant: {
    name: string
    unit: string
    email: string
    phone: string
    move_in_date: string
    lease_start: string
    lease_end: string
    rent_amount: number
    balance_due: number
    late_payment_count: number
    previous_delinquency: boolean
    last_payment_date: string
  }
  property: {
    name: string
    address: string
  }
  interventions: {
    type: string
    sent_at: string
    status: string
  }[]
  generatedDate: string
  managerName?: string
}

function typeLabel(type: string): string {
  const map: Record<string, string> = {
    card_expiry_alert: "Card Expiry Alert",
    split_pay_offer: "Split-Payment Offer",
    cash_for_keys: "Cash for Keys Offer",
    legal_packet: "Legal Notice Sent",
  }
  return map[type] || type
}

export async function generateLegalPacket(data: LegalPacketData): Promise<Uint8Array> {
  const doc = await PDFDocument.create()
  const helvetica = await doc.embedFont(StandardFonts.Helvetica)
  const helveticaBold = await doc.embedFont(StandardFonts.HelveticaBold)

  const BLACK = rgb(0, 0, 0)
  const GRAY = rgb(0.4, 0.4, 0.4)
  const LIGHT_GRAY = rgb(0.9, 0.9, 0.9)
  const RED = rgb(0.8, 0.1, 0.1)
  const BLUE = rgb(0.1, 0.3, 0.7)

  const page = doc.addPage([612, 792]) // Letter size
  const { width, height } = page.getSize()
  let y = height - 50

  function drawLine(color = LIGHT_GRAY) {
    page.drawLine({
      start: { x: 50, y },
      end: { x: width - 50, y },
      thickness: 0.5,
      color,
    })
    y -= 12
  }

  function text(str: string, x: number, size = 10, bold = false, color = BLACK) {
    page.drawText(str, {
      x,
      y,
      size,
      font: bold ? helveticaBold : helvetica,
      color,
    })
  }

  function row(label: string, value: string, bold = false) {
    text(label, 50, 9, false, GRAY)
    text(value, 220, 9, bold, BLACK)
    y -= 16
  }

  // ── Header ───────────────────────────────────────────────────────────────────
  text("COURT-READY LEDGER & EVIDENCE PACKET", 50, 14, true, BLUE)
  y -= 6
  text("Generated by RentSentry Revenue Protection Platform", 50, 9, false, GRAY)
  y -= 6
  text(`Date Generated: ${data.generatedDate}`, 50, 9, false, GRAY)
  y -= 20
  drawLine(BLUE)

  // ── Property & Tenant Info ───────────────────────────────────────────────────
  y -= 4
  text("PROPERTY INFORMATION", 50, 11, true)
  y -= 18
  row("Property Name:", data.property.name)
  row("Property Address:", data.property.address || "Not provided")
  y -= 8

  text("TENANT INFORMATION", 50, 11, true)
  y -= 18
  row("Tenant Name:", data.tenant.name, true)
  row("Unit:", data.tenant.unit)
  row("Email:", data.tenant.email || "Not on file")
  row("Phone:", data.tenant.phone || "Not on file")
  row("Move-In Date:", data.tenant.move_in_date || "Unknown")
  row("Lease Start:", data.tenant.lease_start || "Unknown")
  row("Lease End:", data.tenant.lease_end || "Unknown")

  y -= 8
  drawLine()

  // ── Financial Summary ────────────────────────────────────────────────────────
  y -= 4
  text("FINANCIAL SUMMARY", 50, 11, true)
  y -= 18
  row("Monthly Rent:", `$${data.tenant.rent_amount.toLocaleString()}`)
  row("Total Balance Due:", `$${data.tenant.balance_due.toLocaleString()}`, true)
  row("Late Payment Count:", `${data.tenant.late_payment_count} occurrences`)
  row("Prior Delinquency:", data.tenant.previous_delinquency ? "Yes — on record" : "No")
  row("Last Payment Date:", data.tenant.last_payment_date || "Unknown")

  // Balance due box
  y -= 4
  page.drawRectangle({
    x: 50,
    y: y - 28,
    width: width - 100,
    height: 36,
    color: rgb(0.95, 0.9, 0.9),
    borderColor: RED,
    borderWidth: 1,
  })
  text(`TOTAL AMOUNT OWED: $${data.tenant.balance_due.toLocaleString()}`, 60, 13, true, RED)
  y -= 44
  drawLine()

  // ── Intervention Timeline ────────────────────────────────────────────────────
  y -= 4
  text("INTERVENTION TIMELINE (Good Faith Record)", 50, 11, true)
  y -= 6
  text("The following interventions were attempted prior to legal action:", 50, 9, false, GRAY)
  y -= 20

  if (data.interventions.length === 0) {
    text("No prior interventions recorded.", 50, 9, false, GRAY)
    y -= 16
  } else {
    for (const inv of data.interventions) {
      const dateStr = inv.sent_at
        ? new Date(inv.sent_at).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
        : "Pending"
      text(`•  ${typeLabel(inv.type)}`, 55, 9, true)
      text(`Sent: ${dateStr}  |  Status: ${inv.status}`, 220, 9, false, GRAY)
      y -= 16
    }
  }

  y -= 8
  drawLine()

  // ── Declaration ──────────────────────────────────────────────────────────────
  y -= 4
  text("DECLARATION", 50, 11, true)
  y -= 18

  const declaration = [
    `I, the undersigned property manager, declare under penalty of perjury that the`,
    `information contained in this ledger is true and correct to the best of my knowledge.`,
    `This packet has been prepared for the purpose of initiating legal proceedings against`,
    `the above-named tenant for non-payment of rent in the amount stated above.`,
  ]

  for (const line of declaration) {
    text(line, 50, 9, false, GRAY)
    y -= 14
  }

  y -= 24
  page.drawLine({ start: { x: 50, y }, end: { x: 280, y }, thickness: 0.5, color: BLACK })
  y -= 14
  text("Property Manager Signature", 50, 9, false, GRAY)
  text(`Date: ________________________`, 310, 9, false, GRAY)

  y -= 30
  page.drawLine({ start: { x: 50, y }, end: { x: 280, y }, thickness: 0.5, color: BLACK })
  y -= 14
  text("Printed Name & Title", 50, 9, false, GRAY)

  // ── Footer ───────────────────────────────────────────────────────────────────
  page.drawText("Generated by RentSentry · rentsentry.com · For legal purposes only — consult a licensed attorney.", {
    x: 50,
    y: 30,
    size: 7,
    font: helvetica,
    color: GRAY,
  })

  return doc.save()
}
